spring:
  application:
    name: Eureka_Server
  profiles:
    active: peer1
eureka:
  instance:
    # 启用 IP 偏好模式
    prefer-ip-address: true
  server:
    peer-node-read-timeout-ms: 10000
# 日志输出级别
logging:
  level:
    root: warn
    cn.ok.ecs: info